<?php
/**
 * Dictionnaire français → anglais livré avec l'extension.
 *
 * Une ligne par texte du site, tel qu'il s'affiche en français.
 * Le propriétaire peut compléter ou corriger ces traductions dans
 * Réglages → Version anglaise, sans toucher à ce fichier.
 *
 * @package VillaRaffyEnglish
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(

	/* ─── Barre du haut, menu, en-tête ─── */
	'Aller au contenu'                                                          => 'Skip to content',
	'Saint-Robert, Lot-et-Garonne · Réservation en direct, sans commission'    => 'Saint-Robert, Lot-et-Garonne · Book direct, no commission',
	'Navigation principale'                                                     => 'Main navigation',
	'Ouvrir le menu'                                                            => 'Open menu',
	'La villa'                                                                  => 'The villa',
	'Chambres'                                                                  => 'Rooms',
	'Formules & tarifs'                                                         => 'Options & rates',
	'Piscine & jardin'                                                          => 'Pool & garden',
	'Avis'                                                                      => 'Reviews',
	'La région'                                                                 => 'The area',
	'Contact'                                                                   => 'Contact',
	'Réserver en direct'                                                        => 'Book direct',

	/* ─── Grande image d'accueil ─── */
	'Saint-Robert · Entre Agen et Villeneuve-sur-Lot'                           => 'Saint-Robert · Between Agen and Villeneuve-sur-Lot',
	'Votre oasis d\'exception au cœur du Lot-et-Garonne'                        => 'Your exceptional oasis in the heart of Lot-et-Garonne',
	'Villa de 180 m² pour 8 voyageurs — piscine, jacuzzi, plage privée de sable fin, salle de sport et cinéma privé, sur 2300 m² de nature clôturée.' => 'A 180 m² villa for 8 guests — pool, hot tub, private sandy beach, gym and private cinema, set in 2,300 m² of enclosed grounds.',
	'Arrivée'                                                                   => 'Check-in',
	'Départ'                                                                    => 'Check-out',
	'Voyageurs'                                                                 => 'Guests',
	'Date d\'arrivée'                                                           => 'Check-in date',
	'Date de départ'                                                            => 'Check-out date',
	'Nombre de voyageurs'                                                       => 'Number of guests',
	'1 voyageur'                                                                => '1 guest',
	'2 voyageurs'                                                               => '2 guests',
	'3 voyageurs'                                                               => '3 guests',
	'4 voyageurs'                                                               => '4 guests',
	'5 voyageurs'                                                               => '5 guests',
	'6 voyageurs'                                                               => '6 guests',
	'7 voyageurs'                                                               => '7 guests',
	'8 voyageurs'                                                               => '8 guests',
	'Rechercher'                                                                => 'Search',
	'Ou commencez par découvrir la villa'                                       => 'Or start by discovering the villa',
	'4,86/5 · Coup de cœur voyageurs Airbnb'                                    => '4.86/5 · Airbnb Guest Favourite',
	'Noté 5 étoiles sur Google'                                                 => 'Rated 5 stars on Google',
	'Réservation en direct, sans commission'                                    => 'Book direct, no commission',

	/* ─── Chiffres clés ─── */
	'de villa de plain-pied'                                                    => 'single-storey villa',
	'voyageurs'                                                                 => 'guests',
	'chambres & suites'                                                         => 'bedrooms & suites',
	'de terrain clos'                                                           => 'of enclosed grounds',
	'de piscine, bar immergé'                                                   => 'pool with swim-up bar',
	'5 places'                                                                  => '5 seats',
	'de jacuzzi'                                                                => 'hot tub',

	/* ─── Réserver en direct ─── */
	'Pourquoi réserver en direct ?'                                             => 'Why book direct?',
	'Ici, pas d\'intermédiaire.'                                                => 'No middleman here.',
	'Juste vous, et la villa.'                                                  => 'Just you, and the villa.',
	'Le meilleur tarif, garanti'                                                => 'Best rate, guaranteed',
	'En réservant en direct, vous évitez les commissions des plateformes, qui atteignent 15 %. C\'est toujours ici que le prix est le plus doux.' => 'By booking direct you avoid platform commissions of up to 15%. The best price is always right here.',
	'Un échange direct avec vos hôtes'                                          => 'Direct contact with your hosts',
	'Nous vous répondons personnellement et rapidement, et nous préparons votre arrivée. Petites attentions sur demande — jusqu\'aux huîtres et fruits frais livrés directement à la villa.' => 'We reply personally and quickly, and we prepare your arrival. Little extras on request — right down to fresh oysters and fruit delivered straight to the villa.',
	'Souplesse et simplicité'                                                   => 'Flexible and simple',
	'Horaires d\'arrivée, demandes particulières, séjours sur mesure : tout se règle en un appel ou un message, sans intermédiaire.' => 'Arrival times, special requests, tailor-made stays: everything is settled with one call or message, no middleman.',
	'Une question ? Appelez directement le'                                     => 'A question? Call us directly on',

	/* ─── Visite guidée ─── */
	'La visite guidée'                                                          => 'The guided tour',
	'Poussez la porte, laissez-vous guider'                                     => 'Step inside, let us guide you',
	'Visite guidée de la villa'                                                 => 'Guided tour of the villa',
	'Espace jour'                                                               => 'Living areas',
	'Espace nuit'                                                               => 'Bedrooms',
	'L\'étage'                                                                  => 'Upstairs',
	'Les extérieurs'                                                            => 'Outdoors',
	'Le séjour cathédrale'                                                      => 'The cathedral living room',
	'70 m² baignés de lumière, où les longues tablées s\'éternisent.'           => '70 m² bathed in light, where long dinners linger late.',
	'La cuisine & son bar'                                                      => 'The kitchen & its bar',
	'Équipée pour les chefs, pensée pour l\'apéro.'                             => 'Equipped for chefs, designed for aperitifs.',
	'Écran géant 3,5 m'                                                         => '3.5 m giant screen',
	'Canal+, PlayStation et 3,5 mètres de diagonale pour des soirées mémorables.' => 'Canal+, PlayStation and a 3.5-metre screen for memorable evenings.',
	'Le coin cheminée'                                                          => 'The fireside corner',
	'La flamme qui réchauffe les soirées d\'hiver, un plaid et un bon livre.'   => 'A warm fire on winter evenings, a blanket and a good book.',
	'Suite Serenity'                                                            => 'Serenity Suite',
	'Lit 160 × 200, salle d\'eau privative, et la salle de sport attenante.'    => '160 × 200 bed, private shower room, and the gym next door.',
	'Chambre Urban Chic'                                                        => 'Urban Chic Room',
	'Ouverte sur la verdure, à deux pas du séjour. Le calme absolu.'            => 'Opening onto greenery, steps from the living room. Absolute calm.',
	'Chambre Fleur de Charme'                                                   => 'Fleur de Charme Room',
	'Un cocon de douceur au format Queen Size.'                                 => 'A soft cocoon with a queen-size bed.',
	'Suite Refuge des Lumières'                                                 => 'Refuge des Lumières Suite',
	'25 m² d\'intimité • Salle d\'eau & terrasse privées • Accès direct à la piscine, au jacuzzi et aux espaces extérieurs.' => '25 m² of privacy • Private shower room & terrace • Direct access to the pool, hot tub and gardens.',
	'25 m² d\'intimité • Salle d\'eau & terrasse privées • Accès direct à la piscine, au jacuzzi et aux espaces extérieurs' => '25 m² of privacy • Private shower room & terrace • Direct access to the pool, hot tub and gardens',
	'La salle de sport'                                                         => 'The gym',
	'Vélo, elliptique, rameur, banc de musculation : la forme, même en vacances.' => 'Bike, elliptical, rowing machine, weight bench: stay in shape, even on holiday.',
	'La piscine & son bar immergé'                                              => 'The pool & its swim-up bar',
	'9 mètres plein sud, un cocktail les pieds dans l\'eau.'                    => '9 metres facing due south, a cocktail with your feet in the water.',
	'Le jacuzzi sous les étoiles'                                               => 'The hot tub under the stars',
	'5 places pour prolonger la nuit, éclairages compris.'                      => '5 seats to make the night last, lighting included.',
	'Plage privée & jardin exotique'                                            => 'Private beach & exotic garden',
	'Sable fin, kiosque zen, trois terrasses et un terrain de pétanque.'        => 'Fine sand, a zen pavilion, three terraces and a pétanque court.',
	'Faites défiler pour visiter les 12 espaces'                                => 'Scroll to visit all 12 spaces',
	'Photo précédente'                                                          => 'Previous photo',
	'Photo suivante'                                                            => 'Next photo',
	'Photo 1'                                                                   => 'Photo 1',
	'Photo 2'                                                                   => 'Photo 2',
	'Photo 3'                                                                   => 'Photo 3',

	/* ─── La villa ─── */
	'Un séjour de 70 m² où la vie s\'installe naturellement'                    => 'A 70 m² living room where life settles in naturally',
	'Poussez la porte : le séjour cathédrale de 70 m² s\'ouvre sur une cuisine équipée et son bar, pensés pour les longues tablées d\'été comme pour les soirées d\'hiver au coin du feu. Côté détente, l\'écran géant de 3,5 m transforme le salon en salle de cinéma privée.' => 'Step inside: the 70 m² cathedral living room opens onto a fully equipped kitchen and its bar, designed for long summer dinners as much as for winter evenings by the fire. For downtime, the 3.5 m giant screen turns the lounge into a private cinema.',
	'De plain-pied, baignée de lumière, la villa regarde la campagne sans aucun vis-à-vis. Familles, couples, tribus d\'amis : chacun y trouve son rythme.' => 'Single-storey and bathed in light, the villa looks out over the countryside with no neighbours in sight. Families, couples, groups of friends: everyone finds their own rhythm here.',
	'Écran géant 3,5 m — Canal+ & PlayStation'                                  => '3.5 m giant screen — Canal+ & PlayStation',
	'Salle de sport privée'                                                     => 'Private gym',
	'Plage privée de sable fin'                                                 => 'Private sandy beach',
	'Cuisine ouverte équipée avec bar'                                          => 'Fully equipped open kitchen with bar',
	'WiFi fibre + espace de travail dédié'                                      => 'Fibre WiFi + dedicated workspace',
	'3 terrasses exposées plein sud'                                            => '3 south-facing terraces',
	'Animaux acceptés (sous conditions)'                                        => 'Pets welcome (conditions apply)',
	'Terrain entièrement clos et privé'                                         => 'Fully enclosed private grounds',

	/* ─── Les chambres ─── */
	'Les chambres'                                                              => 'The rooms',
	'Quatre chambres, quatre lits grand format, zéro compromis'                 => 'Four bedrooms, four king-size beds, zero compromise',
	'Toutes les chambres sont équipées d\'une literie grand confort 160 × 200. Les deux suites disposent de leur salle d\'eau privative, les deux autres chambres partagent une salle de bain.' => 'Every bedroom has a 160 × 200 premium bed. The two suites have their own private shower room; the other two bedrooms share a bathroom.',
	'Lit 160 × 200 · salle d\'eau privative · accès direct à la salle de sport' => '160 × 200 bed · private shower room · direct access to the gym',
	'Le refuge des parents : un grand lit, une salle d\'eau rien qu\'à vous, et la salle de sport attenante pour commencer la journée en douceur.' => 'The parents\' retreat: a large bed, a shower room all to yourself, and the gym next door to ease into the day.',
	'Lit 160 × 200 · plain-pied · salle de bain partagée'                       => '160 × 200 bed · ground floor · shared bathroom',
	'Une chambre au caractère affirmé, ouverte sur la verdure, à deux pas du séjour et de la terrasse. Le calme absolu de Saint-Robert.' => 'A room with real character, opening onto greenery, steps from the living room and the terrace. The absolute calm of Saint-Robert.',
	'Un cocon de douceur au format Queen Size'                                  => 'A soft cocoon with a queen-size bed',
	'Lit Queen Size 160 × 200 et literie grand confort, de plain-pied. Elle partage sa salle de bain avec la chambre Urban Chic.' => 'Queen-size 160 × 200 bed with premium bedding, on the ground floor. It shares its bathroom with the Urban Chic Room.',
	'À l\'étage, 25 m² d\'indépendance totale : literie modulable, salle d\'eau privative et terrasse ouvrant directement sur la piscine et le jardin.' => 'Upstairs, 25 m² of total independence: flexible bedding, a private shower room and a terrace opening directly onto the pool and garden.',

	/* ─── Deux façons de séjourner ─── */
	'Deux façons de séjourner'                                                  => 'Two ways to stay',
	'La villa entière, ou la version cocooning'                                 => 'The whole villa, or the cocooning version',
	'Villa complète · toute la saison'                                          => 'Whole villa · all season',
	'La villa complète'                                                         => 'The whole villa',
	'Les 180 m² et les 2300 m² de parc rien que pour vous : 4 chambres, jusqu\'à 8 voyageurs, piscine, jacuzzi, plage privée, salle de sport et cinéma. La formule idéale pour les familles et les tribus d\'amis.' => 'The 180 m² villa and 2,300 m² grounds all to yourself: 4 bedrooms, up to 8 guests, pool, hot tub, private beach, gym and cinema. The ideal option for families and groups of friends.',
	'par nuit en basse saison'                                                  => 'per night in low season',
	'arrivées et départs libres'                                                => 'flexible check-in and check-out days',
	'par nuit en haute saison'                                                  => 'per night in high season',
	'du samedi au samedi, soit 2 450 € la semaine'                              => 'Saturday to Saturday, i.e. €2,450 per week',
	'Jusqu\'à 8 voyageurs · 4 chambres'                                         => 'Up to 8 guests · 4 bedrooms',
	'Toutes les prestations incluses'                                           => 'All amenities included',
	'Grandes tablées, soirées piscine, pétanque'                                => 'Big dinners, pool evenings, pétanque',
	'Réserver la villa complète'                                                => 'Book the whole villa',
	'Formule Cocooning · basse saison'                                          => 'Cocooning option · low season',
	'La version cocooning'                                                      => 'The cocooning version',
	'Un privilège rare de basse saison : la villa entièrement privatisée pour 2 à 4 personnes. Deux chambres restent fermées, et vous gardez la piscine, le jacuzzi, l\'intégralité du jardin et le calme absolu, rien que pour vous.' => 'A rare low-season privilege: the entire villa, privately yours, for 2 to 4 people. Two bedrooms stay closed, and you keep the pool, the hot tub, the whole garden and absolute peace, all to yourself.',
	'par nuit, mai, juin et septembre'                                          => 'per night in May, June and September',
	'Jusqu\'à 4 voyageurs · 2 chambres ouvertes'                                => 'Up to 4 guests · 2 bedrooms open',
	'Villa et extérieurs 100 % privatisés'                                      => 'Villa and grounds 100% private',
	'Parfaite pour les couples et petits comités'                               => 'Perfect for couples and small groups',
	'Réserver en cocooning'                                                     => 'Book the cocooning option',

	/* ─── Piscine, plage & jardin ─── */
	'Piscine, plage & jardin'                                                   => 'Pool, beach & garden',
	'Un cocktail au bar immergé,'                                               => 'A cocktail at the swim-up bar,',
	'les pieds dans l\'eau'                                                     => 'feet in the water',

	/* ─── Vidéo ─── */
	'La villa en mouvement'                                                     => 'The villa in motion',
	'Trente secondes pour tomber sous le charme'                                => 'Thirty seconds to fall under its spell',
	'Diaporama des espaces de la villa'                                         => 'Slideshow of the villa\'s spaces',

	/* ─── Avis ─── */
	'Ils ont séjourné à la villa'                                               => 'They stayed at the villa',
	'Nos voyageurs le disent mieux que nous'                                    => 'Our guests say it better than we do',
	'sur Airbnb · Coup de cœur voyageurs'                                       => 'on Airbnb · Guest Favourite',
	'Voir les avis'                                                             => 'See the reviews',
	'sur Google'                                                                => 'on Google',
	'en propreté, arrivée et qualité-prix'                                      => 'for cleanliness, check-in and value',
	'de réponse, en moins d\'une heure'                                         => 'response rate, within the hour',
	'Voir nos avis sur Airbnb (nouvelle fenêtre)'                               => 'See our Airbnb reviews (new window)',
	'Voir nos avis sur Google (nouvelle fenêtre)'                               => 'See our Google reviews (new window)',
	'Avis 5 étoiles · Airbnb'                                                   => '5-star review · Airbnb',
	'· Mai 2026'                                                                => '· May 2026',
	'· Mai 2025'                                                                => '· May 2025',
	'« Excellent séjour. Magnifique maison. Intérieur et extérieur conformes à la description. Une bulle de dépaysement. Merci à nos hôtes pour leur réactivité et leur bienveillance. Nous recommandons ce lieu à 400 pour cent. »' => '“An excellent stay. A magnificent house. Inside and out, exactly as described. A bubble of escape. Thank you to our hosts for their responsiveness and kindness. We recommend this place 400 percent.”',
	'« Tout était réuni pour passer un très bon séjour : une literie impeccable, des équipements de qualité et un logement parfaitement agréable. Mention spéciale pour les huîtres et crevettes ultra fraîches commandées directement auprès de Stéphane. Des hôtes attentionnés et disponibles. »' => '“Everything was there for a great stay: impeccable bedding, quality equipment and a thoroughly pleasant home. Special mention for the ultra-fresh oysters and prawns ordered directly from Stéphane. Attentive, available hosts.”',
	'« La maison de Stéphane est pratique et assez spacieuse pour être à 8 personnes. Les extérieurs sont topissime !! Je recommande vivement. »' => '“Stéphane\'s house is practical and spacious enough for 8 people. The outdoor areas are amazing!! I highly recommend it.”',
	'« Maison intérieur et extérieur magique, je reviendrai. Des personnes très accueillantes, nous avons passé un week-end au top. »' => '“A magical house, inside and out. I\'ll be back. Very welcoming people, we had a fantastic weekend.”',

	/* ─── Réservation (calendrier) ─── */
	'Réservation'                                                               => 'Booking',
	'Choisissez vos dates, la villa vous attend'                                => 'Choose your dates, the villa awaits',
	'Choisissez votre formule, votre arrivée puis votre départ : le tarif s\'affiche immédiatement. Votre demande part directement chez vos hôtes — par téléphone, WhatsApp ou email — sans aucune commission.' => 'Choose your option, your check-in and then your check-out date: the rate appears instantly. Your request goes straight to your hosts — by phone, WhatsApp or email — with no commission whatsoever.',
	'Formule de séjour'                                                         => 'Stay option',
	'Villa complète'                                                            => 'Whole villa',
	'4 chambres · jusqu\'à 8 voyageurs'                                         => '4 bedrooms · up to 8 guests',
	'Formule Cocooning'                                                         => 'Cocooning option',
	'2 chambres · jusqu\'à 4 voyageurs · basse saison'                          => '2 bedrooms · up to 4 guests · low season',
	'sélection'                                                                 => 'selection',
	'réservé'                                                                   => 'booked',
	'fermé'                                                                     => 'closed',
	'Mois précédent'                                                            => 'Previous month',
	'Mois suivant'                                                              => 'Next month',
	'Du 1er juillet au 31 août : arrivées et départs le samedi, 7 nuits minimum.' => 'From 1 July to 31 August: check-in and check-out on Saturdays, 7 nights minimum.',
	'— choisissez une date —'                                                   => '— choose a date —',
	'Moins de voyageurs'                                                        => 'Fewer guests',
	'Plus de voyageurs'                                                         => 'More guests',
	'Durée'                                                                     => 'Length of stay',
	'Tarif indicatif pour la formule'                                           => 'Indicative rate for the',
	', confirmé par vos hôtes. Aucune commission, aucun frais de service.'      => ' option, confirmed by your hosts. No commission, no service fees.',
	'Demander sur WhatsApp'                                                     => 'Ask on WhatsApp',
	'Envoyer par email'                                                         => 'Send by email',
	'Réponse rapide et personnelle de vos hôtes. Réserver en direct, c\'est le meilleur tarif garanti — sans les frais de service des plateformes.' => 'A quick, personal reply from your hosts. Booking direct means the best rate, guaranteed — without platform service fees.',

	/* ─── La région ─── */
	'Idéalement placée entre Agen et Villeneuve-sur-Lot'                        => 'Ideally located between Agen and Villeneuve-sur-Lot',
	'Vous êtes au centre exact du Lot-et-Garonne. La position parfaite pour rayonner : marchés, bastides, vignobles et baignades.' => 'You are at the very centre of Lot-et-Garonne. The perfect base for exploring: markets, bastide towns, vineyards and swimming spots.',
	'Agen, à 20 minutes'                                                        => 'Agen, 20 minutes away',
	'La capitale du pruneau, ses ruelles, son musée des Beaux-Arts et les berges de Garonne. Marchés gourmands le samedi matin, restaurants et golf à un quart d\'heure de la villa.' => 'The prune capital, with its narrow streets, fine-arts museum and the banks of the Garonne. Gourmet markets on Saturday mornings, restaurants and golf a quarter of an hour from the villa.',
	'Villeneuve-sur-Lot & la vallée du Lot'                                     => 'Villeneuve-sur-Lot & the Lot valley',
	'Bastide médiévale, marché couvert, balades en gabarre sur le Lot. Et tout autour, les plus beaux villages de France : Pujols, Penne-d\'Agenais, Monflanquin.' => 'A medieval bastide town, a covered market, boat trips on the Lot. And all around, some of the most beautiful villages in France: Pujols, Penne-d\'Agenais, Monflanquin.',
	'La campagne du Lot-et-Garonne'                                             => 'The Lot-et-Garonne countryside',
	'Vergers de pruniers, tournesols, chemins de randonnée et routes à vélo au départ de la villa. Le Sud-Ouest authentique, entre Bordeaux et Toulouse.' => 'Plum orchards, sunflowers, hiking trails and cycling routes right from the villa. The authentic South-West, between Bordeaux and Toulouse.',
	'Saint-Robert, Nouvelle-Aquitaine, France — entre Agen et Villeneuve-sur-Lot' => 'Saint-Robert, Nouvelle-Aquitaine, France — between Agen and Villeneuve-sur-Lot',
	'Ouvrir dans Google Maps'                                                   => 'Open in Google Maps',
	'Carte de localisation de la villa'                                         => 'Map showing the villa\'s location',

	/* ─── FAQ ─── */
	'Questions fréquentes'                                                      => 'Frequently asked questions',
	'Tout ce que vous voulez savoir'                                            => 'Everything you want to know',
	'Où se trouve la Villa Raffy exactement ?'                                  => 'Where exactly is Villa Raffy?',
	'À Saint-Robert (47340), en Lot-et-Garonne, à mi-chemin entre Agen et Villeneuve-sur-Lot — environ 20 km de chacune des deux villes. Vous êtes au calme absolu de la campagne, tout en restant à 20 minutes des commerces, restaurants et marchés.' => 'In Saint-Robert (47340), Lot-et-Garonne, halfway between Agen and Villeneuve-sur-Lot — about 20 km from each town. You are in the absolute calm of the countryside, yet only 20 minutes from shops, restaurants and markets.',
	'Combien de personnes la villa peut-elle accueillir ?'                      => 'How many people can the villa accommodate?',
	'La Villa Raffy accueille jusqu\'à 8 voyageurs dans 4 chambres, toutes équipées d\'une literie grand confort 160 × 200 cm. Les deux suites disposent chacune de leur salle d\'eau privative, tandis que les deux autres chambres se partagent une salle de bain. Un lit bébé est également disponible sur demande. En basse saison, la formule Cocooning accueille de 2 à 4 personnes à tarif doux.' => 'Villa Raffy sleeps up to 8 guests in 4 bedrooms, all with premium 160 × 200 cm beds. The two suites each have their own private shower room, while the other two bedrooms share a bathroom. A cot is also available on request. In low season, the Cocooning option welcomes 2 to 4 people at a gentler rate.',
	'La piscine est-elle adaptée aux enfants ?'                                 => 'Is the pool suitable for children?',
	'Oui : la piscine fait 9 × 3,50 m avec une profondeur unique de 1,30 m, idéale pour les enfants accompagnés. Le terrain de 2300 m² est entièrement clos.' => 'Yes: the pool measures 9 × 3.5 m with a single depth of 1.3 m, ideal for supervised children. The 2,300 m² grounds are fully enclosed.',
	'Les animaux sont-ils acceptés ?'                                           => 'Are pets allowed?',
	'Oui, vos compagnons sont acceptés sous conditions : signalez simplement leur présence lors de votre demande. Le terrain clos leur permet de profiter en liberté et en sécurité. À noter : les fêtes ne sont pas autorisées.' => 'Yes, your companions are welcome under certain conditions: simply mention them in your request. The enclosed grounds let them roam freely and safely. Please note: parties are not allowed.',
	'Comment se passe l’arrivée ?'                                              => 'How does check-in work?',
	'Comment se passe l\'arrivée ?'                                             => 'How does check-in work?',
	'Nous accueillons personnellement chaque voyageur à son arrivée à la Villa Raffy. Nous prenons le temps de vous faire découvrir la villa, ses équipements et les espaces extérieurs afin que vous profitiez pleinement de votre séjour dès les premiers instants.' => 'We personally welcome every guest on arrival at Villa Raffy. We take the time to show you around the villa, its facilities and the outdoor areas so that you enjoy your stay to the full from the very first moments.',
	'Qu’est-ce que la formule Cocooning ?'                                      => 'What is the Cocooning option?',
	'Qu\'est-ce que la formule Cocooning ?'                                     => 'What is the Cocooning option?',
	'En basse saison (mai, juin et septembre), la villa est proposée en configuration intimiste pour 2 à 4 personnes : deux chambres restent fermées, et vous disposez de la villa et de l\'intégralité du jardin, piscine et jacuzzi compris. En haute saison, la villa se réserve en entier, du samedi au samedi.' => 'In low season (May, June and September), the villa is offered in an intimate configuration for 2 to 4 people: two bedrooms stay closed, and you have the villa and the whole garden, pool and hot tub included. In high season, the villa is booked as a whole, Saturday to Saturday.',
	'Pourquoi réserver en direct plutôt que sur une plateforme ?'               => 'Why book direct rather than through a platform?',
	'En direct, vous évitez les frais de service des plateformes, qui peuvent atteindre 15 % du séjour. Vous échangez directement avec vos hôtes, qui répondent personnellement et rapidement.' => 'Booking direct, you avoid platform service fees, which can reach 15% of the stay. You deal directly with your hosts, who reply personally and quickly.',
	'Qu’est-ce qui est inclus dans la location ?'                               => 'What is included in the rental?',
	'Qu\'est-ce qui est inclus dans la location ?'                              => 'What is included in the rental?',
	'La location comprend l\'ensemble des équipements de la Villa Raffy : piscine avec bar immergé, jacuzzi 5 places, salle de sport équipée, écran cinéma 3,50 m avec Canal+, cuisine entièrement équipée, trois terrasses, parking privé et Wi-Fi haut débit. Le linge de maison et de toilette est fourni. Vous bénéficiez également d\'un accueil personnalisé à votre arrivée afin de découvrir la villa et ses équipements dans les meilleures conditions. Tout est pensé pour que vous profitiez pleinement de votre séjour, en toute sérénité.' => 'The rental includes all of Villa Raffy\'s facilities: pool with swim-up bar, 5-seat hot tub, fully equipped gym, 3.5 m cinema screen with Canal+, fully equipped kitchen, three terraces, private parking and high-speed Wi-Fi. Bed linen and towels are provided. You also enjoy a personal welcome on arrival to discover the villa and its facilities in the best conditions. Everything is designed so that you can enjoy your stay to the full, with complete peace of mind.',

	/* ─── Pied de page ─── */
	'Votre prochain séjour d\'exception commence ici'                           => 'Your next exceptional stay starts here',
	'Un appel, un message — et la villa est à vous. Vos hôtes vous répondent personnellement.' => 'One call, one message — and the villa is yours. Your hosts reply personally.',
	'Vérifier les disponibilités'                                               => 'Check availability',
	'Écrire sur WhatsApp'                                                       => 'Message us on WhatsApp',
	'Location de villa de luxe avec piscine, jacuzzi, salle de sport et cinéma privé en Lot-et-Garonne, entre Agen et Villeneuve-sur-Lot.' => 'Luxury villa rental with pool, hot tub, gym and private cinema in Lot-et-Garonne, between Agen and Villeneuve-sur-Lot.',
	'Le séjour & la cuisine'                                                    => 'Living room & kitchen',
	'Piscine, jacuzzi & jardin'                                                 => 'Pool, hot tub & garden',
	'Avis des voyageurs'                                                        => 'Guest reviews',
	'Location saisonnière de standing'                                          => 'Premium holiday rental',
	'Nos avis Google (nouvelle fenêtre)'                                        => 'Our Google reviews (new window)',
	'Notre annonce Airbnb (nouvelle fenêtre)'                                   => 'Our Airbnb listing (new window)',

	/* ─── Référencement ─── */
	': villa de luxe avec piscine, jacuzzi, salle de sport et cinéma privé à Saint-Robert, Lot-et-Garonne. Réservez en direct au meilleur tarif, sans commission.' => ': luxury villa with pool, hot tub, gym and private cinema in Saint-Robert, Lot-et-Garonne. Book direct at the best rate, with no commission.',
	'Villa Raffy : villa de luxe avec piscine, jacuzzi, salle de sport et cinéma privé à Saint-Robert, Lot-et-Garonne. Réservez en direct au meilleur tarif, sans commission.' => 'Villa Raffy: luxury villa with pool, hot tub, gym and private cinema in Saint-Robert, Lot-et-Garonne. Book direct at the best rate, with no commission.',
	'fr_FR'                                                                     => 'en_GB',

	/* ─── Journal et page introuvable ─── */
	'Journal'                                                                   => 'Journal',
	'Nos conseils pour profiter du Lot-et-Garonne, les nouvelles de la villa et les bonnes adresses du coin.' => 'Our tips for enjoying Lot-et-Garonne, news from the villa and the best local addresses.',
	'Lire la suite'                                                             => 'Read more',
	'Page non trouvée'                                                          => 'Page not found',
	'Cette page n\'existe pas'                                                  => 'This page does not exist',
	'Le lien que vous avez suivi n\'est plus valable, mais la villa, elle, est toujours là.' => 'The link you followed is no longer valid, but the villa is still very much here.',
	'Retour à l\'accueil'                                                       => 'Back to the home page',
);
